// Tax data for major countries - UPDATED VERSION
// Generated by scripts/tax_data_updater.py on 2025-09-27 20:47:46
//
// CHANGES SUMMARY:
// - Added: 0 countries (none)
// - Modified: 5 countries (australia, brazil, argentina, austria, latvia)
// - Removed: 40 countries (united_states, canada, united_kingdom, germany, france, italy, spain, sweden, norway, denmark, russia, china, india, japan, south_korea, singapore, thailand, indonesia, south_africa, nigeria, egypt, saudi_arabia, united_arab_emirates, mexico, netherlands, belgium, switzerland, poland, finland, iceland, estonia, lithuania, ukraine, hong_kong, taiwan, mongolia, macau, ireland, portugal, greece)
// - Unchanged: 0 countries

export const taxData = {

  // [MODIFIED] Updated from taxation analysis
  // - Tax brackets updated: 7 -> 8 brackets
  // - VAT rate updated: 20.0% -> 20.0%
  "austria": {
    name: "Austria",
    currency: "EUR",
    system: "progressive",
    countryCode: "AT",
    coordinates: [48.2082, 16.3738],
    brackets: [
      {min: 0, max: 11000, rate: 0},
      {min: 11001, max: 18000, rate: 25},
      {min: 18001, max: 25000, rate: 35},
      {min: 25001, max: 31000, rate: 42},
      {min: 31001, max: 60000, rate: 48},
      {min: 60001, max: 90000, rate: 50},
      {min: 90001, max: 1000000, rate: 55},
      {min: 1000001, max: null, rate: 55},
    ],
    special_taxes: [
      {type: "health_insurance", target: "gross", rate: 3.87, description: "Employee health insurance contribution (health, accident, maternity)"},
      {type: "pension_contribution", target: "gross", rate: 10.2, description: "Employee state pension contribution"},
      {type: "unemployment_insurance", target: "gross", rate: 0.2, description: "Employee unemployment insurance contribution"},
      {type: "occupational_injury_insurance", target: "employer", rate: 1.3, description: "Employer-only occupational injury insurance"},
    ],
    vat: {
      hasVAT: true,
      standard: 20.0,
      reduced: [10.0, 13.0],
      description: "Standard 20.0%",
    },
    notes: "Tax year is calendar year. Personal tax brackets and rates follow the Austrian personal income tax rules; social security contributions are part of employment taxes as listed in special_taxes."
  },

  // [MODIFIED] Updated from taxation analysis
  "australia": {
    name: "Australia",
    currency: "AUD",
    system: "progressive",
    countryCode: "AU",
    coordinates: [-25.2744, 133.7751],
    brackets: [
      {min: 0, max: 18200, rate: 0},
      {min: 18201, max: 45000, rate: 16},
      {min: 45001, max: 135000, rate: 30},
      {min: 135001, max: 190000, rate: 37},
      {min: 190001, max: null, rate: 45},
    ],
    special_taxes: [
      {type: "superannuation", target: "gross", rate: 11.5, description: "Mandatory employer contribution to employee’s superannuation fund (2023-24; rising to 12% from 1 July 2025)"},
      {type: "medicare_levy_surcharge", target: "gross", rate: 1.0, description: "MLS 1% for incomes 90,001–105,000 (single)"},
      {type: "medicare_levy_surcharge", target: "gross", rate: 1.5, description: "MLS 1.5% for incomes 105,001+ (single)"},
      {type: "payroll_tax", target: "gross", rate: 4.85, description: "New South Wales payroll tax 4.85% (threshold ≥ $1.5M)"},
      {type: "payroll_tax", target: "gross", rate: 4.95, description: "South Australia payroll tax 4.95% (threshold ≥ $1.5M)"},
      {type: "payroll_tax", target: "gross", rate: 5.75, description: "Victoria payroll tax 5.75% (threshold ≥ $1.4M)"},
      {type: "payroll_tax", target: "gross", rate: 5.75, description: "Queensland payroll tax 5.75% (threshold ≥ $1.3M)"},
      {type: "payroll_tax", target: "gross", rate: 5.5, description: "Western Australia payroll tax 5.5% (threshold ≥ $1.6M)"},
      {type: "payroll_tax", target: "gross", rate: 4.6, description: "Northern Territory payroll tax 4.6% (threshold ≥ $1.6M)"},
    ],
    vat: {
      hasVAT: true,
      standard: 10.0,
      description: "GST 10.0%",
      notes: "Goods and Services Tax (GST)",
    },
    notes: "Tax year: 1 July – 30 June. Filing due by 31 October. SG to 12% from 1 July 2025; MLS thresholds (single: 90,001; couple: 180,001) apply; GST registration threshold: turnover > 75,000."
  },

  // [MODIFIED] Updated from taxation analysis
  // - Tax brackets updated: 5 -> 5 brackets
  "brazil": {
    name: "Brazil",
    currency: "BRL",
    system: "progressive",
    countryCode: "BR",
    coordinates: [-14.235, -51.9253],
    brackets: [
      {min: 0, max: 2760.0, rate: 0},
      {min: 2760.01, max: 3640.0, rate: 7.5},
      {min: 3640.01, max: 4520.0, rate: 15},
      {min: 4520.01, max: 5400.0, rate: 22.5},
      {min: 5400.01, max: null, rate: 27.5},
    ],
    special_taxes: [
      {type: "social_security", target: "gross", rate: 11, description: "Employee INSS contribution (cap BRL 7,507.49 in 2024)"},
      {type: "employer_social_security", target: "gross", rate: 20, description: "Employer INSS contribution (cap BRL 7,507.49 in 2024)"},
    ],
    vat: {
      hasVAT: true,
      standard: 30.0,
      reduced: [20.0, 17.0, 12.0, 9.25, 7.0, 5.0, 5.0, 4.0, 3.65, 2.0],
      description: "Standard 30.0%",
    },
    notes: "Tax year is calendar year. IRPF brackets updated for inflation in 2024. INSS cap increased to BRL 7,507.49 in 2024."
  },

  // [MODIFIED] Updated from taxation analysis
  // - Tax brackets updated: 10 -> 8 brackets
  // - VAT rate updated: 21.0% -> 21.0%
  "argentina": {
    name: "Argentina",
    currency: "ARS",
    system: "progressive",
    countryCode: "AR",
    coordinates: [-38.4161, -63.6167],
    brackets: [
      {min: 0, max: 5000000, rate: 0},
      {min: 5000001, max: 10000000, rate: 5},
      {min: 10000001, max: 20000000, rate: 10},
      {min: 20000001, max: 35000000, rate: 15},
      {min: 35000001, max: 70000000, rate: 21},
      {min: 70000001, max: 120000000, rate: 23},
      {min: 12000001, max: 200000000, rate: 27},
      {min: 200000001, max: null, rate: 35},
    ],
    special_taxes: [
      {type: "social_security_employee", target: "gross", rate: 3.6, description: "Employee social security contribution"},
      {type: "social_security_employer", target: "gross", rate: 14.17, description: "Employer social security contribution"},
    ],
    vat: {
      hasVAT: true,
      standard: 21.0,
      reduced: [10.0, 5.0],
      description: "Standard 21.0%; reduced rates 10% and 5%; zero-rated 0% and exemptions apply.",
      notes: "Zero-rated VAT applies to exports, health services, education, basic food, public transport, and many financial services.",
    },
    notes: "Tax year is calendar year. 2024 rates and brackets remained unchanged from 2023. The standard deduction was adjusted to ARS 3,300,000 to reflect inflation; deductions for health expenses, education, and mortgage interest available. Income tax is calculated on taxable income after standard deduction and personal exemptions, with liability paid at year end."
  },

  // [MODIFIED] Updated from taxation analysis
  // - Tax brackets updated: 3 -> 1 brackets
  // - VAT rate updated: 21.0% -> 21.0%
  // - Tax system changed: progressive -> flat
  "latvia": {
    name: "Latvia",
    currency: "EUR",
    system: "flat",
    countryCode: "LV",
    coordinates: [56.9496, 24.1052],
    brackets: [
      {min: 0, max: null, rate: 23, description: "Flat personal income tax rate"},
    ],
    special_taxes: [
      {type: "social_security", target: "gross", rate: 22.59, description: "Employer pension and health contributions (lower bound of the band)"},
      {type: "social_security", target: "gross", rate: 24.09, description: "Employer pension and health contributions (upper bound of the band)"},
      {type: "social_security", target: "gross", rate: 10.5, description: "Employee pension and health contributions (lower bound of the band)"},
      {type: "social_security", target: "gross", rate: 11, description: "Employee pension and health contributions (upper bound of the band)"},
    ],
    vat: {
      hasVAT: true,
      standard: 21.0,
      reduced: [12.0],
      description: "Standard 21.0%",
      notes: "12% reduced rate for medications and heating fuel; zero-rated items include education services, medical care, financial transactions, and residential rent within specific limits; non-profit organisations meeting legal criteria may have VAT exempt status.",
    },
    notes: "Tax year 2024: flat personal income tax of 23% on taxable income after standard (€900) and dependent (€1,980) allowances. Social-security contributions are mandatory; they are deductible for tax purposes only to the extent of the standard allowance and capped by the social-security ceiling (€46,600). VAT exemptions and zero-rated items apply as described."
  },

};

// Helper function to get tax rate color for map visualization
export function getTaxRateColor(taxRate) {
  if (taxRate === 0) return '#45d153'; // Tax haven
  if (taxRate <= 15) return 'rgba(78,205,196,0.92)'; // Low
  if (taxRate <= 35) return '#ff8e53'; // Medium
  if (taxRate <= 50) return '#ff6b6b'; // High
  if (taxRate <= 55) return '#ee5a6f'; // Very high
  return '#cc2a41'; // Highest
}

// Helper function to get VAT information for a country
export function getCountryVAT(countryKey) {
  const country = taxData[countryKey];
  return country ? country.vat : null;
}

// Helper function to format VAT information for display
export function formatVATInfo(vatInfo) {
  if (!vatInfo) return 'No VAT information available';

  if (!vatInfo.hasVAT) {
    return vatInfo.notes || 'No VAT system';
  }

  let vatText = `Standard: ${vatInfo.standard}%`;

  if (vatInfo.reduced && vatInfo.reduced.length > 0) {
    vatText += `, Reduced: ${vatInfo.reduced.join('%/')}%`;
  }

  if (vatInfo.zeroRated) {
    vatText += ', Zero-rated items available';
  }

  return vatText;
}
